name = "cobble-server"
author = "zeke51500"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4d2d56f185304c82052a1613462ef83abee127858e89362a4d4ef541bcc6799"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
